### ISSUE TITLE
Use Apples distance() function instead of custom

### ISSUE THREAD

**Issue by RIZY101** [Dameech92/AMEL#92]
https://github.com/Dameech92/AMEL/blob/7c1262dc4f9591c52784fe76d53c917d695bdec5/AMEL/AMEL/Models/RadialCoordinateCalculations.swift#L12-L17

Documentation for this function is located here: https://developer.apple.com/documentation/corelocation/cllocation/1423689-distance

**Comment by rjzins** [comment]
Core Location distance output is in meters, it will need to be divided by 1852 to get nautical miles.
