### ISSUE TITLE
Fix this bearing function so that it works correctly

### ISSUE THREAD

**Issue by RIZY101** [Dameech92/AMEL#93]
https://github.com/Dameech92/AMEL/blob/7c1262dc4f9591c52784fe76d53c917d695bdec5/AMEL/AMEL/Models/RadialCoordinateCalculations.swift#L19-L34

Please note that the function bearing() in the extension to swift located here: https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/CoreLocation/CLLocationExtensions.swift
does the correct calculation. Rather than trying to add/import custom swift extensions I would rather just implement their source code and credit them correctly based on their open source licensing agreement.

**Comment by neil-marcellini** [comment]
I copied and pasted in the calculation from the SwifterSwift CLLocation extension into the getReferencePointBearing function. I modified it to work with lat and lng parameters directly rather than CLLocation. [See branch](https://github.com/Dameech92/AMEL/pull/96)

**Comment by RIZY101** [comment]
@neil-marcellini This looks correct to @rjzins and me. We are going to test locally and if all goes according to plan approve the merge.
